"""empty message

Revision ID: 307dd417a758
Revises: 47dbd9667559
Create Date: 2024-12-13 18:49:41.135572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307dd417a758'
down_revision = '47dbd9667559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
